---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

# Note: below *testing Used only in kitchen on vagrant

suites:
  - name: app
    run_list:
      - recipe[mash::devpkgs]
      - recipe[mash::apptesting]
      - recipe[mash::phpcomposer]
    attributes:
  - name: db
    run_list:
      - recipe[mash::devpkgs]
      - recipe[mash::dbtesting]
    attributes:
